import { Product } from "../models/Product.js";

export const seedProducts = async () => {
  await Product.bulkCreate([
    {
      id: 1,
      name: "Redmi Buds 6",
      image: "/accesories/AirpodsBluetoothRedmiBuds6.webp",
      category: "Accesories",
      price: 38000,
      description: "Auriculares inalámbricos con sonido nítido y buena autonomía.",
      active: true,
      stock: 0,
    },
    {
      id: 2,
      name: "Redmi Buds 8",
      image: "/accesories/AudífonosInalámbricosXiaomiRedmiBuds8.webp",
      category: "Accesories",
      price: 45000,
      description: "Versión mejorada con cancelación de ruido y diseño elegante.",
      active: true,
      stock: 0,
    },
    {
      id: 3,
      name: "Redmi Buds 5 Pro",
      image: "/accesories/AuricularesXiaomiRedmi.webp",
      category: "Accesories",
      price: 105000,
      description:
        "Auriculares inalámbricos con cancelación activa de ruido, sonido de alta calidad y mayor autonomía para uso diario.",
      active: true,
      stock: 0,
    },
    {
      id: 4,
      name: "Xiaomi Portable Power Bank",
      image: "/accesories/CargadorPortátilXiaomi.webp",
      category: "Accesories",
      price: 45000,
      description: "Batería externa de alta capacidad para cargar tus dispositivos.",
      active: true,
      stock: 0,
    },
    {
      id: 5,
      name: "Xiaomi 67W Cargador",
      image: "/accesories/CargadorXiaomi.webp",
      category: "Accesories",
      price: 43000,
      description: "Cargador rápido de 67W compatible con múltiples dispositivos.",
      active: true,
      stock: 0,
    },
    {
      id: 6,
      name: "Smart Band 10",
      image: "/accesories/SmartwachXiaomiMiBand10Glaciar.webp",
      category: "Accesories",
      price: 70500,
      description: "Pulsera inteligente con monitoreo de salud y actividad.",
      active: true,
      stock: 0,
    },
    {
      id: 7,
      name: "Redmi Watch 5 Lite",
      image: "/accesories/SmartwatchXiaomiRedmi5Lite.webp",
      category: "Accesories",
      price: 81000,
      description: "Smartwatch liviano con funciones deportivas y notificaciones.",
      active: true,
      stock: 0,
    },
    {
      id: 8,
      name: "Watch 5 Active",
      image: "/accesories/SmartwatchXiaomiWatch5Active.webp",
      category: "Accesories",
      price: 58000,
      description: "Reloj inteligente con diseño moderno y múltiples sensores.",
      active: true,
      stock: 0,
    },
    {
      id: 9,
      name: "Samsung Galaxy A23",
      image: "/phones/SamsungGalaxyA23.webp",
      category: "Cellphones",
      price: 250000,
      description: "Smartphone equilibrado con buena batería y rendimiento.",
      active: true,
      stock: 0,
    },
    {
      id: 10,
      name: "Xiaomi Poco M7",
      image: "/phones/CelularXiaomiPocoM7.webp",
      category: "Cellphones",
      price: 361000,
      description: "Teléfono económico con gran rendimiento para el día a día.",
      active: true,
      stock: 0,
    },
    {
      id: 11,
      name: "Redmi Note 14 Pro",
      image: "/phones/XiaomiRedmiNote14Pro.webp",
      category: "Cellphones",
      price: 400000,
      description: "Gama media potente con excelente cámara.",
      active: true,
      stock: 0,
    },
    {
      id: 12,
      name: "iPhone 15",
      image: "/phones/Iphone15.webp",
      category: "Cellphones",
      price: 1022000,
      description: "Alto rendimiento, cámara avanzada y ecosistema Apple.",
      active: true,
      stock: 0,
    },
    {
      id: 13,
      name: "iPhone 16",
      image: "/phones/Iphone16.webp",
      category: "Cellphones",
      price: 1800000,
      description: "Nueva generación con mejoras en rendimiento y batería.",
      active: true,
      stock: 0,
    },
    {
      id: 14,
      name: "iPhone 17",
      image: "/phones/Iphone17.webp",
      category: "Cellphones",
      price: 2100000,
      description: "Última tecnología con diseño renovado y máxima potencia.",
      active: true,
      stock: 0,
    },
    {
      id: 15,
      name: "Samsung Galaxy A36",
      image: "/phones/SamsungGalaxyA36.webp",
      category: "Cellphones",
      price: 615000,
      description: "Excelente opción de gama media con buen desempeño.",
      active: true,
      stock: 0,
    },
    
  ]);

  console.log("Productos insertados correctamente.");
};
